"""Prompt and annotation pipeline namespace."""
from .schema import AnnotationValidationError, load_annotation_schema, validate_annotation
from .assembly import SemanticPayloadError, assemble_semantic_payload
from .migration import migrate_v1_to_v1_1
from .schema_v1_1 import load_annotation_schema_v1_1, validate_annotation_v1_1
from .rc1 import (
    LEGACY_SHORT_PAYLOAD_ID,
    RC1_PROMPT_ID,
    RC1_SCHEMA_PATH,
    RC1_TOP_LEVEL_FIELDS,
    Rc1GenerationPolicy,
    Rc1ParseResult,
    build_legacy_p3_v1_3_compat_view,
    load_rc1_schema,
    parse_rc1_json,
    should_retry_rc1,
    validate_rc1_shared_facts,
)
from .rc2 import (
    RC2_PROMPT_ID,
    RC2_SCHEMA_PATH,
    RC2_TOP_LEVEL_FIELDS,
    Rc2GenerationPolicy,
    Rc2LanguageResult,
    Rc2ParseResult,
    check_rc2_language,
    load_rc2_schema,
    parse_rc2_json,
    should_retry_rc2,
    validate_rc2_shared_facts,
    validate_rc2_schema,
    validate_rc2_structure,
)
from .rc3 import (
    RC3_CANONICAL_SCHEMA_ID,
    RC3_CANONICAL_SCHEMA_PATH,
    RC3_PAYLOAD_SCHEMA_ID,
    RC3_PAYLOAD_SCHEMA_PATH,
    RC3_PROMPT_ID,
    RC3_TOP_LEVEL_FIELDS,
    Rc3CanonicalContext,
    Rc3LanguageResult,
    Rc3ParseResult,
    canonicalize_rc3,
    check_rc3_language,
    parse_rc3_json,
    rc3_canonical_schema,
    rc3_payload_schema,
    rc3_prompt_skeleton,
    should_retry_rc3,
    validate_rc3_canonical,
    validate_rc3_payload,
)
from .rc4 import (
    RC4_CANONICAL_SCHEMA_ID,
    RC4_CANONICAL_SCHEMA_PATH,
    RC4_PAYLOAD_SCHEMA_ID,
    RC4_PAYLOAD_SCHEMA_PATH,
    RC4_PROMPT_ID,
    RC4_TOP_LEVEL_FIELDS,
    Rc4CanonicalContext,
    Rc4LanguageResult,
    Rc4ParseResult,
    canonicalize_rc4,
    check_rc4_language,
    parse_rc4_json,
    rc4_canonical_schema,
    rc4_payload_schema,
    rc4_prompt_skeleton,
    should_retry_rc4,
    validate_rc4_canonical,
    validate_rc4_payload,
)
from .phase2b import (
    CANONICAL_SCHEMA_ID as PHASE2B_CANONICAL_SCHEMA_ID,
    MEDIA_FIELDS as PHASE2B_MEDIA_FIELDS,
    MEDIA_PROMPT_VERSION,
    MEDIA_SCHEMA_ID,
    MEDIA_SCHEMA_PATH,
    PHASE2B_PIPELINE_VERSION,
    SEMANTIC_FIELDS as PHASE2B_SEMANTIC_FIELDS,
    SEMANTIC_PROMPT_VERSION,
    SEMANTIC_SCHEMA_ID,
    SEMANTIC_SCHEMA_PATH,
    CANONICAL_SCHEMA_PATH as PHASE2B_CANONICAL_SCHEMA_PATH,
    CanonicalContext as Phase2bCanonicalContext,
    canonicalize_phase2b,
    detect_policy_overrides,
    final_canonical_schema as phase2b_final_canonical_schema,
    media_router_schema,
    parse_stage_json,
    prompt_skeleton as phase2b_prompt_skeleton,
    semantic_payload_schema,
    should_retry_stage,
    validate_final_canonical as validate_phase2b_final_canonical,
    validate_media_router,
    validate_semantic_payload as validate_phase2b_semantic_payload,
)
from .semantic import validate_semantic_payload

__all__ = [
    "AnnotationValidationError",
    "SemanticPayloadError",
    "assemble_semantic_payload",
    "load_annotation_schema",
    "load_annotation_schema_v1_1",
    "load_rc1_schema",
    "parse_rc1_json",
    "should_retry_rc1",
    "validate_rc1_shared_facts",
    "load_rc2_schema",
    "parse_rc2_json",
    "should_retry_rc2",
    "check_rc2_language",
    "validate_rc2_structure",
    "validate_rc2_schema",
    "validate_rc2_shared_facts",
    "build_legacy_p3_v1_3_compat_view",
    "RC1_SCHEMA_PATH",
    "RC1_PROMPT_ID",
    "LEGACY_SHORT_PAYLOAD_ID",
    "RC1_TOP_LEVEL_FIELDS",
    "Rc1GenerationPolicy",
    "Rc1ParseResult",
    "RC2_SCHEMA_PATH",
    "RC2_PROMPT_ID",
    "RC2_TOP_LEVEL_FIELDS",
    "Rc2GenerationPolicy",
    "Rc2LanguageResult",
    "Rc2ParseResult",
    "RC3_PROMPT_ID",
    "RC3_PAYLOAD_SCHEMA_ID",
    "RC3_CANONICAL_SCHEMA_ID",
    "RC3_PAYLOAD_SCHEMA_PATH",
    "RC3_CANONICAL_SCHEMA_PATH",
    "RC3_TOP_LEVEL_FIELDS",
    "Rc3CanonicalContext",
    "Rc3LanguageResult",
    "Rc3ParseResult",
    "canonicalize_rc3",
    "check_rc3_language",
    "parse_rc3_json",
    "rc3_canonical_schema",
    "rc3_payload_schema",
    "rc3_prompt_skeleton",
    "should_retry_rc3",
    "validate_rc3_canonical",
    "validate_rc3_payload",
    "RC4_PROMPT_ID",
    "RC4_PAYLOAD_SCHEMA_ID",
    "RC4_CANONICAL_SCHEMA_ID",
    "RC4_PAYLOAD_SCHEMA_PATH",
    "RC4_CANONICAL_SCHEMA_PATH",
    "RC4_TOP_LEVEL_FIELDS",
    "Rc4CanonicalContext",
    "Rc4LanguageResult",
    "Rc4ParseResult",
    "canonicalize_rc4",
    "check_rc4_language",
    "parse_rc4_json",
    "rc4_canonical_schema",
    "rc4_payload_schema",
    "rc4_prompt_skeleton",
    "should_retry_rc4",
    "validate_rc4_canonical",
    "validate_rc4_payload",
    "PHASE2B_PIPELINE_VERSION",
    "MEDIA_PROMPT_VERSION",
    "SEMANTIC_PROMPT_VERSION",
    "MEDIA_SCHEMA_ID",
    "SEMANTIC_SCHEMA_ID",
    "PHASE2B_CANONICAL_SCHEMA_ID",
    "MEDIA_SCHEMA_PATH",
    "SEMANTIC_SCHEMA_PATH",
    "PHASE2B_CANONICAL_SCHEMA_PATH",
    "PHASE2B_MEDIA_FIELDS",
    "PHASE2B_SEMANTIC_FIELDS",
    "Phase2bCanonicalContext",
    "canonicalize_phase2b",
    "detect_policy_overrides",
    "phase2b_final_canonical_schema",
    "media_router_schema",
    "parse_stage_json",
    "phase2b_prompt_skeleton",
    "semantic_payload_schema",
    "should_retry_stage",
    "validate_phase2b_final_canonical",
    "validate_media_router",
    "validate_phase2b_semantic_payload",
    "migrate_v1_to_v1_1",
    "validate_annotation",
    "validate_annotation_v1_1",
    "validate_semantic_payload",
]
